services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: "localhost"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - "8929:8929"
      - "8000:80"
      - "8822:22"
    volumes:
        - ./data/docker/gitlab/etc/gitlab:/etc/gitlab
        - ./data/docker/gitlab/var/opt/gitlab:/var/opt/gitlab
        - ./data/docker/gitlab/var/log/gitlab:/var/log/gitlab
volumes:
  gitlab-runner-config:
    external: true
